USER airflow

# Install necessary Python packages, including Kubernetes client
RUN pip install --no-cache-dir \
    mlflow==2.11.3 \
    pandas>=2.0.0 \
    scikit-learn>=1.3.0 \
    boto3>=1.28.0 \
    apache-airflow-providers-docker>=3.0.0 \
    apache-airflow-providers-cncf-kubernetes>=7.0.0 \
    kubernetes>=28.1.0 # Add kubernetes client

# Expose Airflow webserver port
EXPOSE 8080

# Define default command for the container (can be overridden)
CMD ["airflow", "standalone"] 